apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmscope-api
  labels:
    app: llmscope-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llmscope-api
  template:
    metadata:
      labels:
        app: llmscope-api
    spec:
      containers:
      - name: api
        image: llmscope/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: llmscope-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: llmscope-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llmscope-api-service
spec:
  selector:
    app: llmscope-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
